### PR TITLE
Proposed Setup

### PR DESCRIPTION
**Pull request by jrmadsen**
- See README.md
- Matrix-multiplication test implemented
- In general:
  - Two submodules are built:
    - `instrument_benchmark.enabled` and `instrument_benchmark.disabled`
    - These provide access to the tests
  - Write a small `cmake/UserSettings.cmake` to import instrumentation API
  - Provide`user/instrumentation.h` and `user/instrumentation.hpp` that defines macros

### CODE REVIEW

**Comment by jrmadsen** [comment]
For some reason, it won't let me add Josef as a reviewer. Maybe he has to accept the collaborators request first

**Comment by weidendo** [comment]
> For some reason, it won't let me add Josef as a reviewer. 

Maybe. Just accepted your invitation.

**Comment by weidendo** [comment]
> define INSTRUMENT_CREATE(...)
> define INSTRUMENT_START(...)
> define INSTRUMENT_STOP(...)

As I understand, with this you try to build an abstraction over all possible implementations of instrumentation libraries we may add in this repo. It seems difficult to me to come up first with such an abstraction without knowing what functionality we want to cover. And we should have benchmarks for each functionality. Not each implementation may support each such functionality.

I would propose to start with instrumented versions of benchmarks which directly use the proposed way of that instrumentation library. In an additional step, we can add a version using a common API. 

I see that for benchmarking, we need to have a common way how to specify what should be run as part of the benchmark. I would propose that for each (benchmark/implementation) variant we can specify an arbitrary list of tags which is mapped to runs, used by the python test runner script. The reason is that there may be more than just runs for "disabled" and "enabled" (e.g. to understand how good dynamic throttling/filtering works for automatic overhead control...).

Comments?

**Comment by jrmadsen** [comment]
Ugh, wrote a reply somewhere but guess I didn't post it. 

If you take a look at the README, for timemory and C++, I don't actually even implement:

```cpp
#define INSTRUMENT_CREATE(...)
#define INSTRUMENT_STOP(...)
```
and for C, I don't implement
```c
#define INSTRUMENT_CREATE(...)
```

It seems like to me, this is decent starting point although probably not the final "common" instrumentation API we would want

> I would propose that for each (benchmark/implementation) variant we can specify an arbitrary list of tags which is mapped to runs, used by the python test runner script.

Is this idea somehow different than just having a python dictionary that maps a key to a list of args?

**Comment by jrmadsen** [comment]
I'll go ahead and post it here:

This was the C version for timemory:
```c
#if !defined(USE_INST)
#    define INSTRUMENT_CREATE(...)
#    define INSTRUMENT_START(...)
#    define INSTRUMENT_STOP(...)
#else
#    define INSTRUMENT_CREATE(...)
#    define INSTRUMENT_START(name) void* timer = TIMEMORY_AUTO_TIMER(name);
#    define INSTRUMENT_STOP(name) FREE_TIMEMORY_AUTO_TIMER(timer);
#endif
```
and the C++ version for timemory:
```cpp
#if !defined(USE_INST)
#    define INSTRUMENT_CREATE(...)
#    define INSTRUMENT_START(...)
#    define INSTRUMENT_STOP(...)
#else
using namespace tim::component;
using auto_timer_t = tim::auto_tuple<real_clock, cpu_clock, peak_rss>;
#    define INSTRUMENT_CREATE(...)
#    define INSTRUMENT_START(name) TIMEMORY_POINTER(auto_timer_t, "_", name);
#    define INSTRUMENT_STOP(...)
#endif
```
and those macros (`TIMEMORY_POINTER` and `TIMEMORY_AUTO_TIMER`) use `__FILE__`, `__func__`, and `__LINE__` themselves so it actually enables a lot of freedom...

**Comment by daboehme** [comment]
Hi all,

This looks like a good start to me, thanks @jrmadsen!

I think @weidendo meant that the macro interface needs to be sufficiently flexible to cover pretty much all possible instrumentation libraries. We should look at some and come up with a good scheme. In addition to generic macros, we can also add specialized ones that only a subset of libraries might support, like loop annotations.

Generally, I'd like to extend the framework so that we can add a whole bunch of instrumentation implementations at once and compare them against each other. So instead of just a single user config, you could have a whole list and have the framework build binaries for all of them. 

There's also a lot more different benchmarks we can add, e.g. for deeply/wide nested regions, long names, overlapping regions, explicit loop annotations, etc.

This framework is a really good starting point though and it seems it can be easily extended to do that.

**Review by daboehme — APPROVED** [review]
See earlier comment ...

**Comment by jrmadsen** [comment]
@daboehme I think I have come up with a way to support a multi-user config. Essentially, it will be somewhat similar to the current setup except it will be something like:

```cmake
configure_submodule(
    INTERFACE_LIBRARY timemory-config
    SUBMODULE_NAME timemory
    HEADER_FILE .user/timemory.hpp
    # etc...
)

configure_submodule(
    INTERFACE_LIBRARY caliper-config
    SUBMODULE_NAME caliper
    HEADER_FILE user/caliper.hpp
    # etc...
)

configure_submodule(
    INTERFACE_LIBRARY caliper-mpi-config
    SUBMODULE_NAME caliper_mpi
    HEADER_FILE user/caliper-mpi.hpp
    # etc...
)
```

and essentially the above would generate a python submodule for each instance, use some `configure_file(... @ONLY)` to patch the files as needed, build, and then once that is done, it could even be looped through with something like:

```python
modules = "@CMAKE_MODULES@"
for modname in modules.split(";"):
    mod = importlib.import_module("bench.{}".format(modname))
    mod.run_suite(...)
```

**Comment by daboehme** [comment]
Looks good. I think it's going to be a great basis for a thorough comparison of different instrumentation APIs. Would be great to get this merged - are we still waiting for anything? @khuck maybe?

**Comment by jrmadsen** [comment]
Yea, let me get the multi-user config set up (will have that done today) and then I'll merge it -- once the build is set up then I think we are all good to go to start adding more tests, etc. 

If anyone could set up a CI script for Travis and/or CircleCI, that would be great. @daboehme @khuck @weidendo Any takers?

**Comment by daboehme** [comment]
I'm happy to add some CI scripts. Probably better to merge it first though.

**Comment by jrmadsen** [comment]
@daboehme Ok I am going to merge this. The new method is _really_ nice! See the end of the top-level README w.r.t. the benchmarking script

**Pull request merged**
